fcu_url: /dev/ttyACM0:115200
gcs_url: udp://0.0.0.0:14555@0.0.0.0:14550

setpoint_attitude:
    use_quaternion: true

local_position:
    tf:
        frame_id: world
        child_frame_id: pixhawk
        send: true
