#!/usr/bin/env python

import rospy

#from algorithm_studSasha_kalman import Algorithm
#from algorithm_testg3m1 import Algorithm
from algorithm_studSasha_kalman_line import Algorithm



#from algorithm_studSasha_traj import Algorithm
#from algorithm_studSasha_line import Algorithm
# from algorithm_with_load_without_reg import Algorithm
# from algorithm_with_load import Algorithm

#from algorithm_01 import Algorithm

# from algorithm_relay import Algorithm
from controller import Controller

if __name__ == '__main__':
    rospy.init_node('px4control')
    controller = Controller()
    algorithm = Algorithm(controller)
    rospy.spin()
